github: [Uwaziman1]
patreon: ''
open_collective: ''
ko_fi: uwaziman1
tidelift: ''
community_bridge: ''
liberapay: ''
issuehunt: ''
lfx_crowdfunding: ''
polar: ''
buy_me_a_coffee: ''
thanks_dev: ''
custom: [
  'https://harambeecore-cloud-fs8hm5mp7qvxdbxnscijw2.streamlit.app/#harambee-core-pilot-dashboard',
  'https://ko-fi.com/uwaziman1'
]
