services:
  - type: web
    name: harambeecore-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GOLDAPI_KEY
        value: goldapi-xxxxxx
      - key: OPENAI_API_KEY
        value: your-openai-key
    build:
      pythonVersion: 3.10
